import express from "express";
import { registerMiddlewares } from "./common/middlewares/middleware.js";
// import { registerSwagger } from "#config/swagger.js";
import { registerRoute } from "#common/config/routes.js";
import { errorHandler } from "./common/middlewares/middleware.js";
const app = express();
registerMiddlewares(app);
// registerSwagger(app);
registerRoute(app);
app.use(errorHandler);
export default app;
